sudo: false
language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
after_success:
  - coveralls
notifications:
  email:
    - gary.rowe@bitcoin-solutions.co.uk
    - jim.burton@bitcoin-solutions.co.uk
    - ken@keepkey.com
    - kartik@keepkey.com
  slack: keepkey:NeKNwXldiqJgFvjGOF3qy58C
